# NX Open Journal — Generated by GenerateNXJournalWithColors.py
# Preset    : KJ66 reference preset
# Generated : 2026-03-15 22:06
# Sections  : [1] Expression updates  [2] Part color randomization
#
# Key outputs : mdot_fuel=4.38 g/s  phi=0.280  gap=16.5 mm  n_vap=6
#
# Inputs used:
#   casing_od_inch = 4.33
#   shaft_tunnel_od_inch = 1.18
#   wall_thickness_mm = 0.5
#   pressure_ratio = 2.2
#   compressor_efficiency = 0.74
#   mass_flow_air_kg_s = 0.23
#   target_tit_k = 1123.0
#   liner_material = 304SS
#   target_inner_annulus_vel = 20.0
#   tau_min_s = 0.0014
#
# Color assignments (rolled at generation time — re-run generator for new colors):
#   Liner group  (outer_liner + inner_liner + front_liner_plates) → NX color 81
#   casing                         → NX color 26
#   shaft_tunnel                   → NX color 91
#
# LINER OD NOTE: outer_liner_od / inner_liner_od are COLD BUILD dimensions.
# The model will expand to the nominal hot dimensions at operating temperature.

import NXOpen


def main():

    theSession  = NXOpen.Session.GetSession()
    workPart    = theSession.Parts.Work

    # ══════════════════════════════════════════════════════════════════════
    # SECTION 1 — EXPRESSION UPDATES
    # ══════════════════════════════════════════════════════════════════════

    unit_mm  = workPart.UnitCollection.FindObject("MilliMeter")
    unit_mm2 = workPart.UnitCollection.FindObject("SquareMilliMeter")

    markId_expr = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    theSession.SetUndoMarkName(markId_expr, "Combustor Expressions Update")

    # --- Locate all expressions ---
    # Outer casing OD
    expression1 = workPart.Expressions.FindObject("casing_od")
    # Outer casing ID
    expression2 = workPart.Expressions.FindObject("casing_id")
    # Nominal wall thickness
    expression3 = workPart.Expressions.FindObject("wall_thickness")
    # Shaft tunnel OD
    expression4 = workPart.Expressions.FindObject("shaft_tunnel_od")
    # Shaft tunnel ID
    expression5 = workPart.Expressions.FindObject("shaft_tunnel_id")
    # Outer liner OD — COLD BUILD. Hot = 96.842
    expression6 = workPart.Expressions.FindObject("outer_liner_od")
    # Outer liner ID
    expression7 = workPart.Expressions.FindObject("outer_liner_id")
    # Outer feed annulus radial gap
    expression8 = workPart.Expressions.FindObject("outer_annulus_gap")
    # Inner liner OD — COLD BUILD. Hot = 62.754
    expression9 = workPart.Expressions.FindObject("inner_liner_od")
    # Inner liner ID
    expression10 = workPart.Expressions.FindObject("inner_liner_id")
    # Inner feed annulus radial gap
    expression11 = workPart.Expressions.FindObject("inner_liner_annulus_gap")
    # Total liner axial length
    expression12 = workPart.Expressions.FindObject("chamber_length")
    # Primary zone length (30%). Secondary = 20.047 mm
    expression13 = workPart.Expressions.FindObject("prim_sec_length")
    # Dilution zone length (40%)
    expression14 = workPart.Expressions.FindObject("dil_length")
    # Combustion annulus radial height H
    expression15 = workPart.Expressions.FindObject("combustion_annulus_radial_height")
    # Outer liner primary hole dia
    expression16 = workPart.Expressions.FindObject("outer_primHole_dia")
    # Inner liner primary hole dia
    expression17 = workPart.Expressions.FindObject("inner_primHole_dia")
    # Outer liner secondary hole dia
    expression18 = workPart.Expressions.FindObject("outer_secHole_dia")
    # Inner liner secondary hole dia
    expression19 = workPart.Expressions.FindObject("inner_secHole_dia")
    # Outer liner dilution hole dia
    expression20 = workPart.Expressions.FindObject("outer_dilHole_dia")
    # Inner liner dilution hole dia
    expression21 = workPart.Expressions.FindObject("inner_dilHole_dia")
    # Primary holes/liner (12 each)
    expression22 = workPart.Expressions.FindObject("primHole_qty")
    # Secondary holes/liner (12 each)
    expression23 = workPart.Expressions.FindObject("secHole_qty")
    # Dilution holes/liner (24 each)
    expression24 = workPart.Expressions.FindObject("dilHole_qty")
    # Outer film holes/row (4 rows)
    expression25 = workPart.Expressions.FindObject("outer_film_hole_qty")
    # Inner film holes/row (4 rows)
    expression26 = workPart.Expressions.FindObject("inner_film_hole_qty")
    # Total film cooling area — 220 holes × 1.2 mm dia
    expression27 = workPart.Expressions.FindObject("film_hole_area")

    # --- Edit all expressions ---
    workPart.Expressions.EditExpressionWithUnits(expression1, unit_mm, "109.982")  # casing_od
    workPart.Expressions.EditExpressionWithUnits(expression2, unit_mm, "108.982")  # casing_id
    workPart.Expressions.EditExpressionWithUnits(expression3, unit_mm, "0.500")  # wall_thickness
    workPart.Expressions.EditExpressionWithUnits(expression4, unit_mm, "29.972")  # shaft_tunnel_od
    workPart.Expressions.EditExpressionWithUnits(expression5, unit_mm, "28.972")  # shaft_tunnel_id
    workPart.Expressions.EditExpressionWithUnits(expression6, unit_mm, "96.150")  # outer_liner_od
    workPart.Expressions.EditExpressionWithUnits(expression7, unit_mm, "95.842")  # outer_liner_id
    workPart.Expressions.EditExpressionWithUnits(expression8, unit_mm, "6.070")  # outer_annulus_gap
    workPart.Expressions.EditExpressionWithUnits(expression9, unit_mm, "62.306")  # inner_liner_od
    workPart.Expressions.EditExpressionWithUnits(expression10, unit_mm, "61.754")  # inner_liner_id
    workPart.Expressions.EditExpressionWithUnits(expression11, unit_mm, "15.891")  # inner_liner_annulus_gap
    workPart.Expressions.EditExpressionWithUnits(expression12, unit_mm, "66.823")  # chamber_length
    workPart.Expressions.EditExpressionWithUnits(expression13, unit_mm, "20.047")  # prim_sec_length
    workPart.Expressions.EditExpressionWithUnits(expression14, unit_mm, "26.729")  # dil_length
    workPart.Expressions.EditExpressionWithUnits(expression15, unit_mm, "16.544")  # combustion_annulus_radial_height
    workPart.Expressions.EditExpressionWithUnits(expression16, unit_mm, "4.48")  # outer_primHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression17, unit_mm, "3.63")  # inner_primHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression18, unit_mm, "6.17")  # outer_secHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression19, unit_mm, "4.99")  # inner_secHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression20, unit_mm, "5.20")  # outer_dilHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression21, unit_mm, "4.20")  # inner_dilHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression22, NXOpen.Unit.Null, "12")  # primHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression23, NXOpen.Unit.Null, "12")  # secHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression24, NXOpen.Unit.Null, "24")  # dilHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression25, NXOpen.Unit.Null, "33")  # outer_film_hole_qty
    workPart.Expressions.EditExpressionWithUnits(expression26, NXOpen.Unit.Null, "22")  # inner_film_hole_qty
    workPart.Expressions.EditExpressionWithUnits(expression27, unit_mm2, "243.0")  # film_hole_area

    objects_expr = [NXOpen.NXObject.Null] * 27
    objects_expr[0] = expression1
    objects_expr[1] = expression2
    objects_expr[2] = expression3
    objects_expr[3] = expression4
    objects_expr[4] = expression5
    objects_expr[5] = expression6
    objects_expr[6] = expression7
    objects_expr[7] = expression8
    objects_expr[8] = expression9
    objects_expr[9] = expression10
    objects_expr[10] = expression11
    objects_expr[11] = expression12
    objects_expr[12] = expression13
    objects_expr[13] = expression14
    objects_expr[14] = expression15
    objects_expr[15] = expression16
    objects_expr[16] = expression17
    objects_expr[17] = expression18
    objects_expr[18] = expression19
    objects_expr[19] = expression20
    objects_expr[20] = expression21
    objects_expr[21] = expression22
    objects_expr[22] = expression23
    objects_expr[23] = expression24
    objects_expr[24] = expression25
    objects_expr[25] = expression26
    objects_expr[26] = expression27

    markId_upd = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Make Up to Date")
    theSession.UpdateManager.MakeUpToDate(objects_expr, markId_upd)
    markId_nx  = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "NX update")
    nErrs_expr = theSession.UpdateManager.DoUpdate(markId_nx)
    theSession.DeleteUndoMark(markId_nx,  "NX update")
    theSession.DeleteUndoMark(markId_upd, None)
    theSession.SetUndoMarkName(markId_expr, "Combustor Expressions Update")

    if nErrs_expr > 0:
        print(f"  WARNING: {nErrs_expr} expression update error(s). Check model for failed features.")
    else:
        print("  [1/2] Expressions updated successfully.")

    # ══════════════════════════════════════════════════════════════════════
    # SECTION 2 — COLOR ASSIGNMENTS
    # ══════════════════════════════════════════════════════════════════════
#
#  If a FindObject call raises an exception, that body name does not exist
#  in the current model.  Update LINER_GROUP / INDIVIDUAL_BODIES in the
#  generator script (GenerateNXJournalWithColors.py) and re-generate.

    # ── Liner group: outer_liner + inner_liner + front_liner_plate(s)
    # ── All receive the same color (NX index 81) ──────────────
    try:
        body_liner_0 = workPart.Bodies.FindObject("EXTRUDE(31)")
        body_liner_1 = workPart.Bodies.FindObject("EXTRUDE(6)")
        body_liner_2 = workPart.Bodies.FindObject("EXTRUDE(4)")
        markId_color_100 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Edit Object Display")
        dispMod_100 = theSession.DisplayManager.NewDisplayModification()
        dispMod_100.ApplyToAllFaces    = True
        dispMod_100.ApplyToOwningParts = False
        dispMod_100.NewColor = 81  # liner group color
        objects_color_100 = [NXOpen.DisplayableObject.Null] * 3
        objects_color_100[0] = body_liner_0
        objects_color_100[1] = body_liner_1
        objects_color_100[2] = body_liner_2
        dispMod_100.Apply(objects_color_100)
        theSession.UpdateManager.DoUpdate(markId_color_100)
        dispMod_100.Dispose()
        print("  Liner group color applied  (NX 81)")
    except NXOpen.NXException as e:
        print(f"  WARNING — liner group: could not find one or more bodies: {e}")
        print("  Check LINER_GROUP names in GenerateNXJournalWithColors.py")

    # ── Individual bodies — each gets its own color ───────────────────────
    # casing → NX color 26
    try:
        body_casing = workPart.Bodies.FindObject("EXTRUDE(2)")
        markId_color_101 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Edit Object Display")
        dispMod_101 = theSession.DisplayManager.NewDisplayModification()
        dispMod_101.ApplyToAllFaces    = True
        dispMod_101.ApplyToOwningParts = False
        dispMod_101.NewColor = 26
        objects_color_101 = [NXOpen.DisplayableObject.Null] * 1
        objects_color_101[0] = body_casing
        dispMod_101.Apply(objects_color_101)
        theSession.UpdateManager.DoUpdate(markId_color_101)
        dispMod_101.Dispose()
        print("  Color applied: casing  (NX 26)")
    except NXOpen.NXException as e:
        print(f"  WARNING — casing: body \"EXTRUDE(2)\" not found: {e}")

    # shaft_tunnel → NX color 91
    try:
        body_shaft_tunnel = workPart.Bodies.FindObject("EXTRUDE(8)")
        markId_color_102 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Edit Object Display")
        dispMod_102 = theSession.DisplayManager.NewDisplayModification()
        dispMod_102.ApplyToAllFaces    = True
        dispMod_102.ApplyToOwningParts = False
        dispMod_102.NewColor = 91
        objects_color_102 = [NXOpen.DisplayableObject.Null] * 1
        objects_color_102[0] = body_shaft_tunnel
        dispMod_102.Apply(objects_color_102)
        theSession.UpdateManager.DoUpdate(markId_color_102)
        dispMod_102.Dispose()
        print("  Color applied: shaft_tunnel  (NX 91)")
    except NXOpen.NXException as e:
        print(f"  WARNING — shaft_tunnel: body \"EXTRUDE(8)\" not found: {e}")

    # ── Save ──────────────────────────────────────────────────────────────
    status = workPart.Save(NXOpen.BasePart.SaveComponents.TrueValue,
                           NXOpen.BasePart.CloseAfterSave.FalseValue)
    status.Dispose()
    print("  [2/2] Colors applied. Part saved.")


if __name__ == "__main__":
    main()
