# NX Open Journal — Generated by GenerateNXJournal.py
# Preset      : 6-inch engine preset
# Generated   : 2026-03-15 01:48
# Source tool : V21_CombustionChamberDesign.py
# Key outputs : mdot_fuel=7.10 g/s  phi=0.214  gap=20.7mm  n_vap=8
#
# Inputs used:
#   casing_od_inch = 6.0
#   shaft_tunnel_od_inch = 1.65
#   wall_thickness_mm = 1.5
#   pressure_ratio = 1.5
#   compressor_efficiency = 0.94
#   mass_flow_air_kg_s = 0.487
#   target_tit_k = 900.0
#   liner_material = 304SS
#
# IMPORTANT — liner OD dimensions are COLD BUILD (room-temperature).
# Parts will expand to their nominal hot dimensions at operating temperature.
# Do NOT substitute the hot dimensions in NX — the thermal offset is already applied.

import NXOpen


def main():

    theSession  = NXOpen.Session.GetSession()
    workPart    = theSession.Parts.Work

    # --- Unit references (fetched once, reused) ---------------------------
    unit_mm  = workPart.UnitCollection.FindObject("MilliMeter")
    unit_mm2 = workPart.UnitCollection.FindObject("SquareMilliMeter")

    # --- Undo mark ---------------------------------------------------------
    markId = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    theSession.SetUndoMarkName(markId, "Combustor Expressions Update")

    # --- Locate all expressions --------------------------------------------
    # Outer casing outside diameter
    expression1 = workPart.Expressions.FindObject("casing_od")
    # Outer casing inside diameter  = casing_od - 2*wall
    expression2 = workPart.Expressions.FindObject("casing_id")
    # Casing and liner nominal wall thickness
    expression3 = workPart.Expressions.FindObject("wall_thickness")
    # Shaft tunnel outside diameter
    expression4 = workPart.Expressions.FindObject("shaft_tunnel_od")
    # Shaft tunnel inside diameter  = shaft_tunnel_od - 2*wall
    expression5 = workPart.Expressions.FindObject("shaft_tunnel_id")
    # Outer liner OD — COLD BUILD dimension (room-temperature machining target). Hot (operating) = 125.617
    expression6 = workPart.Expressions.FindObject("outer_liner_od")
    # Outer liner ID = outer_liner_od - 2*wall_thickness
    expression7 = workPart.Expressions.FindObject("outer_liner_id")
    # Radial width of outer feed annulus (casing ID to outer liner OD)/2
    expression8 = workPart.Expressions.FindObject("outer_annulus_gap")
    # Inner liner OD — COLD BUILD dimension. Hot = 81.211
    expression9 = workPart.Expressions.FindObject("inner_liner_od")
    # Inner liner ID = inner_liner_od - 2*wall_thickness
    expression10 = workPart.Expressions.FindObject("inner_liner_id")
    # Radial width of inner feed annulus (inner liner ID to shaft tunnel OD)/2
    expression11 = workPart.Expressions.FindObject("inner_liner_annulus_gap")
    # Total axial combustion liner length
    expression12 = workPart.Expressions.FindObject("chamber_length")
    # Primary zone axial length (30% of chamber_length). Secondary = 44.904 mm  — update this expression if your NX model uses prim_sec as a combined zone length.
    expression13 = workPart.Expressions.FindObject("prim_sec_length")
    # Dilution zone axial length (40% of chamber_length)
    expression14 = workPart.Expressions.FindObject("dil_length")
    # Radial height of the combustion annulus H = (outer_liner_id - inner_liner_od)/2
    expression15 = workPart.Expressions.FindObject("combustion_annulus_radial_height")
    # Outer liner primary zone hole diameter
    expression16 = workPart.Expressions.FindObject("outer_primHole_dia")
    # Inner liner primary zone hole diameter
    expression17 = workPart.Expressions.FindObject("inner_primHole_dia")
    # Outer liner secondary zone hole diameter
    expression18 = workPart.Expressions.FindObject("outer_secHole_dia")
    # Inner liner secondary zone hole diameter
    expression19 = workPart.Expressions.FindObject("inner_secHole_dia")
    # Outer liner dilution zone hole diameter
    expression20 = workPart.Expressions.FindObject("outer_dilHole_dia")
    # Inner liner dilution zone hole diameter
    expression21 = workPart.Expressions.FindObject("inner_dilHole_dia")
    # Primary holes per liner (outer = inner = 16)
    expression22 = workPart.Expressions.FindObject("primHole_qty")
    # Secondary holes per liner (outer = inner = 16)
    expression23 = workPart.Expressions.FindObject("secHole_qty")
    # Dilution holes per liner (outer = inner = 32)
    expression24 = workPart.Expressions.FindObject("dilHole_qty")
    # Outer liner film cooling holes PER ROW (4 rows × this = 372 total outer film holes)
    expression25 = workPart.Expressions.FindObject("outer_film_hole_qty")
    # Inner liner film cooling holes PER ROW (4 rows × this = 248 total inner film holes)
    expression26 = workPart.Expressions.FindObject("inner_film_hole_qty")
    # Total film cooling hole area both liners combined (hole dia 1.2 mm, 620 holes total)
    expression27 = workPart.Expressions.FindObject("film_hole_area")

    # --- Edit all expressions ----------------------------------------------
    # Values sourced from V21_CombustionChamberDesign.py output.
    workPart.Expressions.EditExpressionWithUnits(expression1, unit_mm, "152.400")  # casing_od
    workPart.Expressions.EditExpressionWithUnits(expression2, unit_mm, "149.400")  # casing_id
    workPart.Expressions.EditExpressionWithUnits(expression3, unit_mm, "1.500")  # wall_thickness
    workPart.Expressions.EditExpressionWithUnits(expression4, unit_mm, "41.910")  # shaft_tunnel_od
    workPart.Expressions.EditExpressionWithUnits(expression5, unit_mm, "38.910")  # shaft_tunnel_id
    workPart.Expressions.EditExpressionWithUnits(expression6, unit_mm, "124.961")  # outer_liner_od
    workPart.Expressions.EditExpressionWithUnits(expression7, unit_mm, "122.617")  # outer_liner_id
    workPart.Expressions.EditExpressionWithUnits(expression8, unit_mm, "11.891")  # outer_annulus_gap
    workPart.Expressions.EditExpressionWithUnits(expression9, unit_mm, "80.787")  # inner_liner_od
    workPart.Expressions.EditExpressionWithUnits(expression10, unit_mm, "78.211")  # inner_liner_id
    workPart.Expressions.EditExpressionWithUnits(expression11, unit_mm, "18.150")  # inner_liner_annulus_gap
    workPart.Expressions.EditExpressionWithUnits(expression12, unit_mm, "149.679")  # chamber_length
    workPart.Expressions.EditExpressionWithUnits(expression13, unit_mm, "44.904")  # prim_sec_length
    workPart.Expressions.EditExpressionWithUnits(expression14, unit_mm, "59.872")  # dil_length
    workPart.Expressions.EditExpressionWithUnits(expression15, unit_mm, "20.703")  # combustion_annulus_radial_height
    workPart.Expressions.EditExpressionWithUnits(expression16, unit_mm, "5.72")  # outer_primHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression17, unit_mm, "4.66")  # inner_primHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression18, unit_mm, "7.88")  # outer_secHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression19, unit_mm, "6.41")  # inner_secHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression20, unit_mm, "8.53")  # outer_dilHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression21, unit_mm, "6.94")  # inner_dilHole_dia
    workPart.Expressions.EditExpressionWithUnits(expression22, NXOpen.Unit.Null, "16")  # primHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression23, NXOpen.Unit.Null, "16")  # secHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression24, NXOpen.Unit.Null, "32")  # dilHole_qty
    workPart.Expressions.EditExpressionWithUnits(expression25, NXOpen.Unit.Null, "93")  # outer_film_hole_qty
    workPart.Expressions.EditExpressionWithUnits(expression26, NXOpen.Unit.Null, "62")  # inner_film_hole_qty
    workPart.Expressions.EditExpressionWithUnits(expression27, unit_mm2, "692.9")  # film_hole_area

    # --- Commit: mark all for update, then regenerate the model -----------
    objects = [NXOpen.NXObject.Null] * 27
    objects[0] = expression1
    objects[1] = expression2
    objects[2] = expression3
    objects[3] = expression4
    objects[4] = expression5
    objects[5] = expression6
    objects[6] = expression7
    objects[7] = expression8
    objects[8] = expression9
    objects[9] = expression10
    objects[10] = expression11
    objects[11] = expression12
    objects[12] = expression13
    objects[13] = expression14
    objects[14] = expression15
    objects[15] = expression16
    objects[16] = expression17
    objects[17] = expression18
    objects[18] = expression19
    objects[19] = expression20
    objects[20] = expression21
    objects[21] = expression22
    objects[22] = expression23
    objects[23] = expression24
    objects[24] = expression25
    objects[25] = expression26
    objects[26] = expression27

    markId_upd = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible,
                                        "Make Up to Date")
    theSession.UpdateManager.MakeUpToDate(objects, markId_upd)

    markId_nx = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible,
                                       "NX update")
    nErrs = theSession.UpdateManager.DoUpdate(markId_nx)

    theSession.DeleteUndoMark(markId_nx,  "NX update")
    theSession.DeleteUndoMark(markId_upd, None)
    theSession.SetUndoMarkName(markId, "Combustor Expressions Update")

    if nErrs > 0:
        print(f"  WARNING: NX reported {nErrs} update error(s). "
              "Check model for failed features.")
    else:
        print("  Expressions updated and model regenerated successfully.")

    # --- Save --------------------------------------------------------------
    status = workPart.Save(NXOpen.BasePart.SaveComponents.TrueValue,
                           NXOpen.BasePart.CloseAfterSave.FalseValue)
    status.Dispose()
    print("  Part saved.")


if __name__ == "__main__":
    main()
